name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        id-token: write
    steps:
      - name: Set JWT Auth Token
        id: auth-token
        run: |
            export TOKEN=$(curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL")
            echo $TOKEN | jq .value | base64
            echo "token=$(echo $TOKEN)" >> $GITHUB_OUTPUT
            
      - name: Troubleshoot Token
        id: grab-token
        run: |
            export TOKEN_JSON=$(echo $GITHUB_OIDC_TOKEN | jq "{ jwt: .value, role: \"$VAULT_ROLE\" }")
            echo $TOKEN_JSON | jq -r '.jwt | split(".") | .[1] | @base64d' | jq
            export VAULT_LOGIN_DATA=$(echo $TOKEN_JSON | curl -sSLf -X PUT -H "Content-Type: application/json" --data @- $VAULT_URL/v1/auth/jwt/login)
            export VAULT_TOKEN=$(echo $VAULT_LOGIN_DATA | jq -r .auth.client_token)
            # echo $VAULT_TOKEN >> $GITHUB_OUTPUT
        env:
          VAULT_ROLE: "myproject-staging"
          VAULT_URL: "https://vault.magserver.com"
          GITHUB_OIDC_TOKEN: ${{ steps.auth-token.outputs.token }}

      - name: Login to Vault
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.magserver.com
          role: myproject-staging
          method: jwt
          jwtGithubAudience: sigstore # set the GitHub token's aud claim
        env:
          vault-token: "TEST" # ${{ steps.grab-token.outputs.VAULT_TOKEN }}
          TF_VAR_vault_token: "test1"
          # method: github
          # githubToken: ${{ secrets.TOKEN || github.token }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
          terraform_wrapper: false
        env:
          TF_VAR_vault_token: "test"

      - name: Terraform Plan
        id: plan
        uses: actions/checkout@v2
        if: github.event_name == 'pull_request'
        # run: terraform plan -no-color
        env:
          TF_VAR_vault_token: "test"