
on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

env:
  # VAULT_ADDR: "https://vault-111.34-83-87-204.sslip.io"
  VAULT_NAMESPACE: "user1"
  
jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Retrieve secret from Vault
        uses: hashicorp/vault-action@v2.4.0
        with:
          exportToken: true
          method: jwt
          path: jwt-github
          url: https://a3b9-184-144-40-103.ngrok.io
          namespace: "root"
          role: "vault-test-570210047"
          secrets: |
            secrets/data/github foo | FOO ;
            secrets/data/github zig | ZIG

      - name: Use secret from Vault
        run: "echo '${{ steps.secrets.outputs.foo }}'" 
  
      
